### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Haroonabdulrazaq** [Haroonabdulrazaq/Node-tutorial#1]
- [x] Add Create BookInstance form
- [x]  Add Update BookInstance form
- [x]  Add Update Book form
- [x]  Add Update Author form
- [x]  Add Update Genre form
- [x] Add Delete Author
- [x] Add Delete Book
- [x] Add Delete BookInstance
- [x] Add Delete Genre
- [x] Update README
- [x] Deploy to Heroku Or any (Cloud Hosting Service)
